// BåtOpplag – ekte opplagsdata, bygget område for område.
//
// Kun verifiserbare opplysninger fra tilbydernes egne sider / offentlige
// oppføringer er lagt inn. Felter som ikke er publisert står som `null`
// ("ukjent") – de er IKKE gjettet. Hver oppføring har en `kilde`-URL.
//
// Feltforklaring:
//   navn          – firmanavn
//   omrade        – område/kommune (gruppering)
//   sted          – stedsnavn (vises til bruker)
//   postnummer    – 4-sifret postnummer (brukes til grov nærhet); "" hvis ukjent
//   adresse       – gateadresse (eller null)
//   nettside      – URL til tilbyderens side (eller null)
//   telefon       – telefonnummer (eller null)
//   plassering    – "innendors" | "utendors" | null
//   temperatur    – "varmt" | "kaldt" | null
//   fuktkontroll  – true | false | null
//   maksLengde    – største båtlengde i fot (number) | null
//   prisPerFot    – flat sesongpris per fot (NOK) | null
//   prisBrackets  – lengdebasert prisliste [{maks, kr}] | null (overstyrer prisPerFot)
//   prisModell    – "perFot" (kr = pris per fot) | "total" (kr = total sesongpris
//                   for båt opp til `maks` fot). Kun relevant med prisBrackets.
//   prisEksMva    – true hvis prisene er oppgitt eks. mva
//   ledigePlasser – antall ledige plasser (number) | null
//   merknad       – kort forbehold som vises på kortet (eller null)
//   tjenester     – liste av tjenestenøkler (kan være tom)
//   kilde         – URL der opplysningene er hentet fra
//
// Gyldige tjenestenøkler (må matche SERVICE_LABELS i app.js):
//   konservering_motor, frostsikring_kjol, spyling, bunnstoff,
//   kranloft, vaskeplass, batterilading

const STORAGE_SITES = [
  // ========================= Lillesand =========================
  {
    navn: "Bjørlykke Bygg & Båtopplag AS",
    omrade: "Lillesand",
    sted: "Lillesand (Svåbekk)",
    postnummer: "4790",
    adresse: "Gamleveien 110, 4790 Lillesand",
    nettside: "https://bjorlykkeas.no",
    telefon: "908 80 680",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: [
      { maks: 20, kr: 415 },
      { maks: 25, kr: 474 },
      { maks: 29, kr: 592 },
      { maks: 34, kr: 703 },
      { maks: 999, kr: 769 },
    ],
    prisModell: "perFot",
    prisEksMva: true,
    ledigePlasser: null,
    merknad: null,
    tjenester: ["konservering_motor", "bunnstoff"],
    kilde: "https://bjorlykkeas.no/priser-kontakt",
  },
  {
    navn: "IB Motorservice AS",
    omrade: "Lillesand",
    sted: "Lillesand",
    postnummer: "4790",
    adresse: "Storemyrheia 1, 4790 Lillesand",
    nettside: "https://www.ib-motor.no",
    telefon: "37 27 24 90",
    plassering: null,
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: ["konservering_motor", "bunnstoff", "vaskeplass"],
    kilde: "https://www.ib-motor.no/vinterlagring/",
  },
  {
    navn: "Lillesand Motorsenter AS",
    omrade: "Lillesand",
    sted: "Lillesand",
    postnummer: "4790",
    adresse: null,
    nettside: "https://www.lillesandmotorsenter.no",
    telefon: null,
    plassering: "innendors",
    temperatur: "varmt", // isolert og frostfri hall
    fuktkontroll: null,
    maksLengde: 30, // "opp til ca. 30 fot"
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: ["konservering_motor"],
    kilde: "https://www.lillesandmotorsenter.no/vinteropplag/",
  },
  {
    navn: "Bjørnevika Bådsenter",
    omrade: "Lillesand",
    sted: "Høvåg (Lillesand)",
    postnummer: "4770",
    adresse: null,
    nettside: "https://bbaad.no",
    telefon: null,
    plassering: "innendors", // syv haller
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: ["konservering_motor"],
    kilde: "https://bbaad.no/batopplag/",
  },
  {
    navn: "Lillesand Båtpleie AS",
    omrade: "Lillesand",
    sted: "Lillesand",
    postnummer: "4790",
    adresse: null,
    nettside: "https://baatpleie.no",
    telefon: null,
    plassering: "innendors",
    temperatur: null, // "frostfri hall" – oppgir ikke varmt/temperert
    fuktkontroll: null,
    maksLengde: 30, // prisliste dekker 10–30 fot
    prisPerFot: null,
    // Faste totalpriser per fot-lengde. Inkluderer spyling under vannlinja,
    // kjøring av motor i ferskvann og lagring i frostfri hall.
    prisBrackets: [
      { maks: 10, kr: 6500 }, { maks: 11, kr: 7000 }, { maks: 12, kr: 7400 },
      { maks: 13, kr: 7800 }, { maks: 14, kr: 8500 }, { maks: 15, kr: 9200 },
      { maks: 16, kr: 10500 }, { maks: 17, kr: 11000 }, { maks: 18, kr: 11500 },
      { maks: 19, kr: 12000 }, { maks: 20, kr: 13000 }, { maks: 21, kr: 14000 },
      { maks: 22, kr: 15000 }, { maks: 23, kr: 16000 }, { maks: 24, kr: 17000 },
      { maks: 25, kr: 18000 }, { maks: 26, kr: 19000 }, { maks: 27, kr: 20000 },
      { maks: 28, kr: 21000 }, { maks: 29, kr: 22000 }, { maks: 30, kr: 23000 },
    ],
    prisModell: "total",
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Prisen inkluderer spyling, motorkjøring i ferskvann og frostfri hall. Endringer kan forekomme – kontakt for eksakt pris.",
    tjenester: ["konservering_motor", "spyling", "vaskeplass", "bunnstoff"],
    kilde: "https://baatpleie.no/priser/",
  },
  {
    navn: "Lillesand Seilforening (Kokkenes)",
    omrade: "Lillesand",
    sted: "Lillesand (Kokkenes)",
    postnummer: "4790",
    adresse: null,
    nettside: "https://www.lillesand-seilforening.no",
    telefon: null,
    plassering: "utendors",
    temperatur: "kaldt",
    fuktkontroll: false,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: [],
    kilde: "https://www.lillesand-seilforening.no/www2/tur-og-hav/batopplag/",
  },

  // ========================= Grimstad =========================
  {
    navn: "Grimstad Bådsenter AS",
    omrade: "Grimstad",
    sted: "Grimstad (Østerhus)",
    postnummer: "4876",
    adresse: "Odden 9, 4876 Grimstad",
    nettside: "https://gbaad.no/batopplag/",
    telefon: "37 04 13 58",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: [],
    kilde: "https://gbaad.no/batopplag/",
  },
  {
    navn: "Båtgarasjer (Hasseltangen AS)",
    omrade: "Grimstad",
    sted: "Fevik (Grimstad)",
    postnummer: "4870",
    adresse: "Sømsveien 183, 4870 Fevik",
    nettside: "https://www.batgarasjer.no",
    telefon: "952 30 702",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: 50,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: ["spyling", "bunnstoff", "kranloft", "vaskeplass"],
    kilde: "https://www.batgarasjer.no/",
  },
  {
    navn: "Grimstad Motorbåtforening (GMF)",
    omrade: "Grimstad",
    sted: "Grimstad (Grømbukta)",
    postnummer: "4877",
    adresse: null,
    nettside: "https://gmf.no/",
    telefon: null,
    plassering: "utendors",
    temperatur: "kaldt",
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    // Faste totalpriser per lengdekategori (uteopplag). Båt over 32 fot: 300 kr/fot.
    prisBrackets: [
      { maks: 14, kr: 1020 },
      { maks: 24, kr: 1440 },
      { maks: 32, kr: 1800 },
    ],
    prisModell: "total",
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Medlemsforening – krever medlemskap. Båt over 32 fot: 300 kr/fot.",
    tjenester: [],
    kilde: "https://gmf.no/priser/",
  },

  // ========================= Arendal =========================
  {
    navn: "Arendal Bådsenter (Abaad)",
    omrade: "Arendal",
    sted: "Stoa (Arendal)",
    postnummer: "4848",
    adresse: "Skrubbedalsveien 2, 4848 Arendal",
    nettside: "https://abaad.no/batopplag/",
    telefon: "464 25 000",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Forsikringsgodkjente haller, reolbasert servicesystem.",
    tjenester: ["spyling", "konservering_motor", "frostsikring_kjol"],
    kilde: "https://abaad.no/batopplag/",
  },
  {
    navn: "Arendal Båt og Motor AS",
    omrade: "Arendal",
    sted: "His (Arendal)",
    postnummer: "4817",
    adresse: "Tangen alle 44, 4817 His",
    nettside: "https://www.arendalbatogmotor.no/batopplag/",
    telefon: "467 04 444",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    // Totalpriser per lengde (inkl. høytrykksspyling, batterilading, oppstartskontroll).
    prisBrackets: [
      { maks: 16, kr: 6810 },
      { maks: 17, kr: 7350 },
      { maks: 18, kr: 7810 },
      { maks: 19, kr: 8390 },
      { maks: 20, kr: 8990 },
      { maks: 21, kr: 9600 },
      { maks: 22, kr: 10250 },
    ],
    prisModell: "total",
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Publisert prisliste dekker 16–22 fot. Større båter: kontakt tilbyder.",
    tjenester: ["spyling", "batterilading"],
    kilde: "https://www.arendalbatogmotor.no/batopplag/",
  },
  {
    navn: "Sjøsenteret Arendal",
    omrade: "Arendal",
    sted: "Stoa (Arendal)",
    postnummer: "4848",
    adresse: "Stoaveien 5A, 4848 Arendal",
    nettside: "https://www.sjosa.no/opplag/",
    telefon: "91 00 95 45",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: 30,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Krever kaskoforsikring.",
    tjenester: ["kranloft"],
    kilde: "https://www.sjosa.no/opplag/",
  },
  {
    navn: "Båthuset Arendal AS",
    omrade: "Arendal",
    sted: "Arendal",
    postnummer: "4841",
    adresse: "Bedriftsveien 18, 4841 Arendal",
    nettside: "https://www.bathusetarendal.no/",
    telefon: "37 03 30 00",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Tørr hall.",
    tjenester: [],
    kilde: "https://www.bathusetarendal.no/",
  },

  // ========================= Kristiansand =========================
  {
    navn: "Kristiansand Båt og Motor AS (KBM)",
    omrade: "Kristiansand",
    sted: "Kristiansand",
    postnummer: "4639",
    adresse: "Kystveien 310, 4639 Kristiansand",
    nettside: "https://www.kbm.no",
    telefon: "38 05 81 00",
    plassering: "innendors",
    temperatur: "varmt", // tørre, frostfrie og oppvarmede haller
    fuktkontroll: null,
    maksLengde: 49, // full prisliste 15–49 fot; 50+ på forespørsel
    prisPerFot: null,
    // Totalpriser per fot-lengde, sesong 2025/2026 (inkl. mva).
    prisBrackets: [
      { maks: 15, kr: 9431 }, { maks: 16, kr: 10202 }, { maks: 17, kr: 12406 },
      { maks: 18, kr: 13438 }, { maks: 19, kr: 14336 }, { maks: 20, kr: 15368 },
      { maks: 21, kr: 16398 }, { maks: 22, kr: 17429 }, { maks: 23, kr: 21343 },
      { maks: 24, kr: 22638 }, { maks: 25, kr: 23937 }, { maks: 26, kr: 25365 },
      { maks: 27, kr: 28750 }, { maks: 28, kr: 30832 }, { maks: 29, kr: 32260 },
      { maks: 30, kr: 34474 }, { maks: 31, kr: 36169 }, { maks: 32, kr: 38516 },
      { maks: 33, kr: 40602 }, { maks: 34, kr: 43338 }, { maks: 35, kr: 45819 },
      { maks: 36, kr: 48298 }, { maks: 37, kr: 50909 }, { maks: 38, kr: 53523 },
      { maks: 39, kr: 56133 }, { maks: 40, kr: 58880 }, { maks: 41, kr: 60974 },
      { maks: 42, kr: 63718 }, { maks: 43, kr: 66597 }, { maks: 44, kr: 69475 },
      { maks: 45, kr: 72616 }, { maks: 46, kr: 75625 }, { maks: 47, kr: 78636 },
      { maks: 48, kr: 79956 }, { maks: 49, kr: 84924 },
    ],
    prisModell: "total",
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Priser for sesong 2025/2026. Båt over 49 fot: pris på forespørsel.",
    tjenester: ["kranloft", "spyling", "bunnstoff"],
    kilde: "https://www.kbm.no/batopplag/innelagring",
  },
  {
    navn: "Randesund Båtsenter",
    omrade: "Kristiansand",
    sted: "Kristiansand",
    postnummer: "4639",
    adresse: "Dvergsnesveien 120, 4639 Kristiansand",
    nettside: "https://www.baatsenteret.no",
    telefon: "416 86 420",
    plassering: "innendors",
    temperatur: "varmt",
    fuktkontroll: true, // oppgir avfukter + oppvarmet/isolert hall
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: ["kranloft", "spyling", "konservering_motor", "bunnstoff"],
    kilde: "https://www.baatsenteret.no/opplag",
  },
  {
    navn: "Kristiansand Bådsenter AS",
    omrade: "Kristiansand",
    sted: "Sørlandsparken (Kristiansand)",
    postnummer: "4636",
    adresse: "Barstølveien 3b, 4636 Kristiansand S",
    nettside: "https://kbaad.no",
    telefon: "40 00 69 96",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    // Kun endepunkter publisert (14 fot / 28 fot), fra eldre prisliste.
    prisBrackets: [
      { maks: 14, kr: 8500 },
      { maks: 28, kr: 21950 },
    ],
    prisModell: "total",
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Prisene er fra en eldre liste (2022/2023) og kun veiledende.",
    tjenester: ["spyling", "kranloft", "bunnstoff", "konservering_motor"],
    kilde: "https://kbaad.no/batopplag/",
  },
  {
    navn: "Bølgen Båtservice AS",
    omrade: "Kristiansand",
    sted: "Kristiansand",
    postnummer: "4639",
    adresse: "Kystveien 655, 4639 Kristiansand S",
    nettside: "https://bolgenbat.no",
    telefon: "482 93 937",
    plassering: "innendors",
    temperatur: null, // tilbyr både temperert og kald hall
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Tilbyr temperert hall, kald hall og utendørs.",
    tjenester: ["konservering_motor", "spyling"],
    kilde: "https://bolgenbat.no/batopplag/",
  },

  // ========================= Oslo / Oslofjorden =========================
  {
    navn: "Sørfonden Slipp AS",
    omrade: "Oslo",
    sted: "Oslo",
    postnummer: "0198",
    adresse: "Dalheimveien 10, 0198 Oslo",
    nettside: "https://www.sorfondenslipp.no",
    telefon: "22 29 56 00",
    plassering: "utendors",
    temperatur: "kaldt",
    fuktkontroll: null,
    maksLengde: 28,
    prisPerFot: null,
    prisBrackets: [
      { maks: 23, kr: 375 },
      { maks: 28, kr: 400 },
    ],
    prisModell: "perFot",
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Seilbåt: 455 kr/fot. I tillegg miljøavgift 400 kr.",
    tjenester: ["spyling", "kranloft"],
    kilde: "https://www.sorfondenslipp.no/vinteropplag-og-vinterhavn",
  },
  {
    navn: "Killingen Båtservice AS",
    omrade: "Oslo",
    sted: "Oslo (Bygdøy)",
    postnummer: "0287",
    adresse: "Killingen 46, 0287 Oslo",
    nettside: "https://www.killingenbatservice.no",
    telefon: "46 622 622",
    plassering: null,
    temperatur: null,
    fuktkontroll: null,
    maksLengde: 50,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: ["kranloft", "spyling"],
    kilde: "https://www.killingenbatservice.no/services-7",
  },
  {
    navn: "Oslo Seilforening",
    omrade: "Oslo",
    sted: "Oslo (Lille Herbern)",
    postnummer: "0214",
    adresse: null,
    nettside: "https://www.osloseilforening.no",
    telefon: "917 91 239",
    plassering: "utendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: 27,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: null,
    tjenester: ["kranloft"],
    kilde: "https://www.osloseilforening.no/next/p/13825/vinteropplag",
  },
  {
    navn: "Holmen Slipp AS",
    omrade: "Oslo",
    sted: "Asker",
    postnummer: "",
    adresse: null,
    nettside: "https://www.holmenslipp.com",
    telefon: null,
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: 40,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Pris beregnes per m² (ute 795 kr/m², inne 1050 kr/m²) pluss vinterpresenning.",
    tjenester: ["kranloft", "spyling"],
    kilde: "https://www.holmenslipp.com/vinteropplag",
  },
  {
    navn: "Opplag Oslo (Tofte)",
    omrade: "Oslo",
    sted: "Tofte",
    postnummer: "",
    adresse: "Tofte Strand Næringspark, Tofte",
    nettside: "http://opplagoslo.no",
    telefon: null,
    plassering: "innendors",
    temperatur: "varmt",
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: 350, // innendørs 350 kr + mva/fot (utendørs 250 kr + mva/fot)
    prisBrackets: null,
    prisModell: null,
    prisEksMva: true,
    ledigePlasser: null,
    merknad: "Utendørs 250 kr/fot. Lagring på Tofte.",
    tjenester: ["konservering_motor"],
    kilde: "http://opplagoslo.no/tofte/yacht.php",
  },
  {
    navn: "Båtopplag Oslo (KAJ AS)",
    omrade: "Oslo",
    sted: "Hønefoss (henting i Oslo)",
    postnummer: "3514",
    adresse: "Nesmoveien 1, 3514 Hønefoss",
    nettside: "https://batopplagoslo.no",
    telefon: "488 55 151",
    plassering: "innendors",
    temperatur: "varmt",
    fuktkontroll: null,
    maksLengde: 28,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Pakkepris etter lengde. Lagring i Hønefoss med henting i Oslo.",
    tjenester: ["konservering_motor", "spyling", "bunnstoff", "batterilading"],
    kilde: "https://batopplagoslo.no",
  },
  {
    navn: "Kompass Marine Services AS",
    omrade: "Oslo",
    sted: "Drøbak",
    postnummer: "1446",
    adresse: "Rogenveien 3b, 1446 Drøbak",
    nettside: "https://www.kompassmarine.com",
    telefon: "902 11 529",
    plassering: "innendors",
    temperatur: "varmt",
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Oppgir «innendørs fra 160 kr/fot».",
    tjenester: ["konservering_motor", "spyling", "bunnstoff"],
    kilde: "https://www.kompassmarine.com/vinteropplag/",
  },

  // ---- Flere Oslo/Oslofjord-tilbydere (lagt til 2026-08-21) ----
  {
    navn: "Asker Marina",
    omrade: "Oslo",
    sted: "Asker",
    postnummer: "",
    adresse: null,
    nettside: "https://askermarina.no/meny/havna/vinteropplag",
    telefon: null,
    plassering: "innendors",
    temperatur: "varmt",
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Oppvarmet båthotell (3500 m²) samt kald innendørs lagring og boblehavn ute. Priser ikke publisert (fås ved kontakt).",
    tjenester: ["kranloft"],
    kilde: "https://askermarina.no/meny/havna/vinteropplag",
  },
  {
    navn: "Drammen Båt AS",
    omrade: "Oslo",
    sted: "Drammen",
    postnummer: "3039",
    adresse: "Svelvikveien 81, 3039 Drammen",
    nettside: "https://www.dbat.no/tjenester/vinteropplag/",
    telefon: null,
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Innendørs lagringshaller. Oppvarming ikke oppgitt. Ingen priser publisert.",
    tjenester: ["konservering_motor", "frostsikring_kjol", "bunnstoff", "batterilading", "spyling"],
    kilde: "https://www.dbat.no/tjenester/vinteropplag/",
  },
  {
    navn: "Oksenøya Marina",
    omrade: "Oslo",
    sted: "Fornebu",
    postnummer: "",
    adresse: null,
    nettside: "https://oksenoyamarina.no/",
    telefon: "23 88 02 09",
    plassering: "innendors",
    temperatur: "varmt",
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Lukket temperert båthall (innendørs) og boblehavn ute. Priser ikke publisert på hovedsiden.",
    tjenester: [],
    kilde: "https://oksenoyamarina.no/",
  },
  {
    navn: "Amundsen Båtslipp AS",
    omrade: "Oslo",
    sted: "Nærsnes",
    postnummer: "3478",
    adresse: "Grundvikveien 1, 3478 Nærsnes",
    nettside: "https://www.amundsenbatslipp.no/bestilling-vinteropplag",
    telefon: "954 11 133",
    plassering: "innendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: true,
    ledigePlasser: null,
    merknad: "Pris per m²: innendørs 620 kr/m², utendørs 375 kr/m² (eks. mva). Kranløft/pall/krybbe kommer i tillegg (løft 1688–3600 kr etter størrelse).",
    tjenester: ["konservering_motor", "frostsikring_kjol", "spyling", "kranloft"],
    kilde: "https://www.amundsenbatslipp.no/bestilling-vinteropplag",
  },
  {
    navn: "Båtpleiebutikken (Heitmann & Søn)",
    omrade: "Oslo",
    sted: "Drøbak",
    postnummer: "1443",
    adresse: "Husvikholmen 8, 1443 Drøbak",
    nettside: "https://www.baatpleiebutikken.no/pages/vinteropplag-i-drobak",
    telefon: null,
    plassering: "utendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: 355,
    prisBrackets: null,
    prisModell: "perFot",
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Utendørs på asfalt. I tillegg: opptak/utsett 408 kr/fot, vask 47 kr/fot, miljøgebyr 625 kr. Vinterstrøm (maks 500W) 8100 kr.",
    tjenester: ["kranloft", "spyling", "frostsikring_kjol", "batterilading"],
    kilde: "https://www.baatpleiebutikken.no/pages/vinteropplag-i-drobak",
  },
  {
    navn: "Grundvik Marina",
    omrade: "Oslo",
    sted: "Tofte (Hurum)",
    postnummer: "3482",
    adresse: "Østre Strandvei 52, 3482 Tofte",
    nettside: "https://grundvikmarina.no/batopplag",
    telefon: "32 79 40 01",
    plassering: "innendors",
    temperatur: "kaldt",
    fuktkontroll: null,
    maksLengde: 37,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Innendørs i godt ventilerte haller (ikke oppvarmet). Maks ca. 8 tonn / 37 fot. Ingen priser publisert.",
    tjenester: ["kranloft", "spyling", "frostsikring_kjol", "konservering_motor", "batterilading"],
    kilde: "https://grundvikmarina.no/batopplag",
  },
  {
    navn: "Bakken Motor",
    omrade: "Oslo",
    sted: "Drammen",
    postnummer: "3036",
    adresse: "Kobbervikdalen 115, 3036 Drammen",
    nettside: "https://bakken-motor.no/verksted_single/prisliste-vinteropplag-og-service/",
    telefon: "32 26 01 80",
    plassering: "utendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: 1350,
    prisBrackets: null,
    prisModell: "perFot",
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Utendørs i reolsystem. Pris inkl. mva og inkluderer spyling, bunnstoff, polering og frostsikring (alt-i-ett). RIB rimeligere (1150–1250 kr/fot). Krymping 295 kr/fot.",
    tjenester: ["spyling", "bunnstoff", "batterilading", "frostsikring_kjol"],
    kilde: "https://bakken-motor.no/verksted_single/prisliste-vinteropplag-og-service/",
  },
  {
    navn: "Østlandske Båtopplag",
    omrade: "Oslo",
    sted: "Son",
    postnummer: "1555",
    adresse: "Kolåsveien 30, 1555 Son",
    nettside: "https://ostlandskebatopplag.no/",
    telefon: "98 81 05 92",
    plassering: "innendors",
    temperatur: "varmt",
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Innendørs i oppvarmede lokaler, 24/7 overvåking. Gratis henting/levering i Son- og Moss-området. Ingen priser publisert.",
    tjenester: [],
    kilde: "https://ostlandskebatopplag.no/",
  },
  {
    navn: "Asker Seilforening",
    omrade: "Oslo",
    sted: "Vettre (Asker)",
    postnummer: "1392",
    adresse: "Blakstad Bryggevei 9, 1392 Vettre",
    nettside: "https://www.askerseil.no/vinteropplag",
    telefon: "404 06 870",
    plassering: "utendors",
    temperatur: null,
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Kun for betalende medlemmer. Pris per m²: 320 kr uten mast, 340 kr med mast (2026/27). Kranløft i oktober.",
    tjenester: ["kranloft"],
    kilde: "https://www.askerseil.no/vinteropplag",
  },
  {
    navn: "Fagerstrand Båtforening",
    omrade: "Oslo",
    sted: "Fagerstrand (Nesodden)",
    postnummer: "",
    adresse: null,
    nettside: "https://www.havneweb.no/fabat/?mod=osv",
    telefon: "90 94 24 80",
    plassering: "innendors",
    temperatur: "kaldt",
    fuktkontroll: null,
    maksLengde: null,
    prisPerFot: null,
    prisBrackets: null,
    prisModell: null,
    prisEksMva: false,
    ledigePlasser: null,
    merknad: "Kaldhall innendørs (også under tak og ute). Pris per m² (2026/27): kaldhall 727 kr, under tak 576 kr, ute 317–331 kr. Åpent for booking (ikke bare medlemmer).",
    tjenester: ["kranloft", "spyling"],
    kilde: "https://www.havneweb.no/fabat/?mod=osv",
  },
];
